name: Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Determine which paths have changed
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          base: main
          filters: |
            library:
              - 'packages/npm-library/**'
            website:
              - 'packages/npm-website/**'
              - 'packages/npm-library/**'
            api:
              - 'packages/npm-api/**'
              - 'packages/npm-library/**'

      # Deploy Website if it has changes
      - name: Deploy Website
        if: steps.changes.outputs.website == 'true'
        run: echo "Deploying Website" # Replace this with your actual deploy command for the website
      - name: List contents of the specified directory
        if: steps.changes.outputs.website == 'true'
        uses: ./.github/actions/ls
        with:
          directory: "packages/npm-website"
      - name: Vercel Production
        if: steps.changes.outputs.website == 'true'
        uses: ./.github/actions/vercel-production
        with:
          directory: "packages/npm-website"

      # Deploy API if it has changes
      - name: Deploy API
        if: steps.changes.outputs.api == 'true'
        run: echo "Deploying API" # Replace this with your actual deploy command for the API
      - name: List contents of the specified directory
        if: steps.changes.outputs.website == 'true'
        uses: ./.github/actions/ls
        with:
          directory: "packages/npm-api"
